[package]
name = "aaws"
version = "0.1.0"
authors = ["Henrik Larsson <henrik.larsson.15@wirelesscar.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.20"
